google.cse.enabled=true
google.cse.apiKey=AIzaSyAKhfLqT3r3YWYfuNjzTZmpUzOpstOihww
google.cse.cx=92de6ed9437f34da1

# Web Server Configuration
server.port=8080

# FreeMarker Template Configuration
spring.freemarker.suffix=.ftlh
spring.freemarker.template-loader-path=classpath:/templates/
spring.freemarker.cache=false
spring.freemarker.charset=UTF-8